#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

SSHFLAGS="${SSHFLAGS:--q -t}"

# this script is run on the VM host


VM="xenial"
if [ $# -ne 0 ]
then
   VM="$1"
   shift
fi

VERSION="10.0.0.0"
if [ $# -ne 0 ]
then
   VERSION="$1"
   shift
fi



# https://stackoverflow.com/questions/37453525/how-can-i-check-specific-server-running-or-notusing-virsh-commands-before-i-s
is_vm_running()
{
   local vm="$1"

   local tmp

   tmp=$(virsh list --all | grep " ${vm} " | awk '{ print $3}')
   if [ "x$tmp" == "x" ] || [ "x$tmp" != "xrunning" ]
   then
      return 1
   fi
   return 0
}


start()
{
   local vm="$1"
   local user="$2"

   if is_vm_running "${vm}"
   then
      return
   fi

   virsh netstart default 2> /dev/null

   while ! is_vm_running "${vm}"
   do
      sleep 1
      virsh start "${vm}" && break
   done

   while ! ssh "${user}@${vm}" true > /dev/null 2>&1
   do
      sleep 1
   done
}


prepare()
{
   local vm="$1"
   local user="$2"
   local version="$3"

   local preparescript

   preparescript="\
   ( [ -d mulle-clang-cpack ] || git clone 'https://github.com/Codeon-GmbH/mulle-clang-cpack.git' ) &&
   ( cd mulle-clang-cpack && git pull )
   "

   ssh ${SSHFLAGS} "${user}@${vm}" "${preparescript}" || exit 1

   local buildscript

   buildscript="VERSION=\"${version}\" ./mulle-clang-cpack/package-build clean download"

   ssh ${SSHFLAGS} "${user}@${vm}" "${buildscript}" || exit 1
}


build()
{
   local vm="$1"
   local user="$2"
   local version="$3"

   local buildscript

   buildscript="VERSION=\"${version}\" ./mulle-clang-cpack/package-build build"
   ssh ${SSHFLAGS} "${user}@${vm}" "${buildscript}" || exit 1
}


verpack()
{
   local vm="$1"
   local user="$2"
   local version="$3"

   local buildscript

   buildscript="VERSION=\"${version}\" ./mulle-clang-cpack/package-build verpack"
   ssh ${SSHFLAGS} "${user}@${vm}" "${buildscript}"  || exit 1
}


download()
{
   local vm="$1"
   local user="$2"
   local version="$3"

   local dist

   dist="$( ssh ${SSHFLAGS} "${user}@${vm}" "lsb_release -sc" )" || exit 1

   local filename

   version="${version%-*}"

   filename="mulle-clang-${version}-${dist}-amd64.deb"
   scp "${user}@${vm}:${filename}" "${filename}"
}


upload()
{
   local vm="$1"
   local user="$2"
   local version="$3"

   local dist

   dist="$( ssh ${SSHFLAGS} "${user}@${vm}" "lsb_release -sc" )" || exit 1

   local filename
   local debname

   debname="main"
   case "${version}" in
      *-*)
         debname="${version#*-}"
         version="${version%-*}"
      ;;
   esac

   filename="mulle-clang-${version}-${dist}-amd64.deb"

   scp "${filename}" "oswald:debian-software/dists/${dist}/${debname}/binary-amd64/"
   # ssh oswald "cd debian-software && ./update.sh && ./upload.sh"
}



main()
{
   while [ $# -ne 0 ]
   do
      echo "////// $1 \\\\\\\\\\\\" >&2
      "$1" "${VM}" "${USER}" "${VERSION}" || exit 1
      shift
   done
}


if [ $# -eq 0 ]
then
   main start prepare build verpack download upload
else
   main "$@"
fi
