#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

# this script is run in the VM

VERSION="${VERSION:-10.0.0.0}"
NAME="${VERSION%-*}"
BRANCH_OR_TAG="${VERSION##*-}"
BRANCH_OR_TAG="${BRANCH_OR_TAG:-release}"
DIST="`lsb_release -sc`"

OPTIONS="--with-lldb --no-compiler-rt"

clean()
{
   if [ -d mulle-clang-lldb ]
   then
      rm -rf mulle-clang-lldb
   fi

   rm *.deb 2> /dev/null

   mkdir mulle-clang-lldb
}


download()
{
   (
      cd mulle-clang-lldb &&
      curl -L -O "https://raw.githubusercontent.com/Codeon-GmbH/mulle-clang/${BRANCH_OR_TAG}/bin/install-mulle-clang" &&
      chmod 755 install-mulle-clang
   )
}


# just here for documentation
# https://askubuntu.com/questions/618474/how-to-install-the-latest-gcurrently-5-1-in-ubuntucurrently-14-04
install_gcc6_on_trusty()
{
   sudo add-apt-repository ppa:ubuntu-toolchain-r/test
   sudo apt-get update
   sudo apt-get install gcc-6 g++-6
   sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 100
   sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100
   sudo update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-6 100
}


build()
{
   (
      cd mulle-clang-lldb &&
      mkdir -p "opt/mulle-clang/${NAME}" &&
      case "${DIST}" in
         precise)
            CC=clang-3.6 CXX=clang++-3.6 ./install-mulle-clang -v --prefix "`pwd`/opt/mulle-clang/${NAME}" ${OPTIONS}
         ;;

	      # trusty needs  g++-6
         *)
            ./install-mulle-clang -v --prefix "`pwd`/opt/mulle-clang/${NAME}" ${OPTIONS}
         ;;
      esac
   )
}


verpack()
{
   cp "mulle-clang-cpack/CMakeLists.txt" \
      "mulle-clang-cpack/generate-package" \
      "mulle-clang-lldb/" &&

   (
      cd mulle-clang-lldb &&
      rm -rf build && # make room for packaging
      chmod 755 generate-package &&
      NAME="${NAME}" VERSION="${VERSION}" ./generate-package &&
      mv "package/mulle-clang-${VERSION}-Linux.deb" "../mulle-clang-${NAME}-${DIST}-amd64.deb" &&

      echo "Debian Package \"mulle-clang-${NAME}-${DIST}-amd64.deb\" ready" >&2
   )
}


upload()
{
   scp "mulle-clang-${NAME}-${DIST}-amd64.deb" \
       "oswald.codeon.de:debian-software/dists/${DIST}/main/binary-amd64/"
}


main()
{
   while [ $# -ne 0 ]
   do
      echo "====== $1 ======" >&2
      if ! "$1"
      then
         echo "$1 failed" >&2
         exit 1
      fi
      shift
   done
}


echo "====== version ======" >&2
echo "VERSION=${VERSION}" >&2

if [ $# -eq 0 ]
then
   main clean download build verpack
else
   main "$@"
fi

